In [50]:
import numpy as np
a=[2,3,5,7,3]
N=3

def vandermonde(arr,N, order):
    print("The given array is: {0}".format(arr))
    if order:
        print("\n\n vandermonde matrix with Ascending order with N is:{0} \n".format(N),'*'*50)
        opM=np.array([x**i for x in arr for i in range(N)])
    else:
        print("\n\n vandermonde matrix with Decending order with N is:{0}\n".format(N),"*"*50)
        opM=np.array([x**(N-i-1) for x in arr for i in range(N)])
    print(opM.reshape(len(a),N))
   

    
vandermonde(a,N,False)
vandermonde(a,N,True)


The given array is: [2, 3, 5, 7, 3]


 vandermonde matrix with Decending order with N is:3
 **************************************************
[[ 4  2  1]
 [ 9  3  1]
 [25  5  1]
 [49  7  1]
 [ 9  3  1]]
The given array is: [2, 3, 5, 7, 3]


 vandermonde matrix with Ascending order with N is:3 
 **************************************************
[[ 1  2  4]
 [ 1  3  9]
 [ 1  5 25]
 [ 1  7 49]
 [ 1  3  9]]


Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values. Question: Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [32]:
#given array
from functools import reduce 

a=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

def movavg(arr,k):
    arr.sort()
    print("Moving avg of arr= {0} \n with window k = {1} is".format(arr,k))
    for ind, v in enumerate(arr):
        s=0
        if ind+k<= len(arr):
            for r in range(k):
                s+=arr[ind+r]
            print(s/3)
    
    
movavg(a,2)   
a

Moving avg of arr= [2, 3, 5, 7, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
 with window k = 2 is
1.6666666666666667
2.6666666666666665
4.0
5.0
6.0
7.0
25.333333333333332
45.666666666666664
51.0
60.0
66.33333333333333
83.33333333333333


[2, 3, 5, 7, 8, 10, 11, 65, 72, 81, 99, 100, 150]